[project]
name = "copier-django-template"
version = "0.1.0"
description = "A modern Copier template for scaffolding a Django project with best practices built-in"
readme = "README.md"
requires-python = "==3.13.*"

dependencies = [
    "copier>=9.11.0",
    "copier-templates-extensions>=0.3.2",
]
